[project]
name = "typst-iso-7000"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.12.0",
    "lxml>=5.0.0",
    "tqdm>=4.67.3",
]
