[project]
name = "typst-iso-7000"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "lxml>=5.0.0",
    "picosvg",
    "tqdm>=4.67.3",
]

[tool.uv.sources]
picosvg = { git = "https://github.com/googlefonts/picosvg" }
